# -*- coding: utf-8 -*-
"""Chatbox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XzVAWh_iqZ2C42VViC3Kc4ARXgRiBwc
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

# Load the dataset
ques = pd.read_csv('/content/kamaraj_college_faq.csv')

# Optional: Check for null values
# print(ques.isnull().sum())

# Remove rows with missing values
ques.dropna(inplace=True)

# Encode textual answers to numerical labels
le = LabelEncoder()
ques['Answer_Label'] = le.fit_transform(ques['Answer'])

# Vectorize the questions
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(ques['Question'])
y = ques['Answer_Label']

# Train logistic regression model
model = LogisticRegression()
model.fit(X, y)

# Get input from user
qu = input("Enter your question: ")

if qu.strip():
    # Vectorize the input question
    user_vector = vectorizer.transform([qu])
    
    # Predict the label
    predicted_label = model.predict(user_vector)[0]
    
    # Convert label back to original answer text
    predicted_answer = le.inverse_transform([predicted_label])[0]
    
    print("Predicted answer:", predicted_answer)
else:
    print("Please enter a valid question.")
