# -*- coding: utf-8 -*-
"""Frontend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtXZPJgDfAboyWxAA0QuOrlqie5o6Ivi
"""

!pip install streamlit

import streamlit as st
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

ques = pd.read_csv('/content/kamaraj_college_faq.csv')

def load_model_and_data():
    ques = pd.read_csv('/content/kamaraj_college_faq.csv')
    ques.dropna(inplace=True)

    le = LabelEncoder()
    ques['Answer'] = le.fit_transform(ques['Answer'])

    vectorizer = TfidfVectorizer()
    a = vectorizer.fit_transform(ques['Question'])
    b = ques['Answer']

    LO = LogisticRegression()
    LO.fit(a, b)
    return LO, vectorizer, le

model, vectorizer, label_encoder = load_model_and_data()

# Streamlit UI
st.title("Kamaraj College FAQ Chatbot")
st.write("Ask any question related to Kamaraj College.")

user_question = st.text_input("Enter your question:")

if st.button("Get Answer"):
    if user_question.strip() == "":
        st.warning("Please enter a question.")
    else:
        po = vectorizer.transform([user_question])
        ans = model.predict(po)
        predicted_answer_label = ans[0]
        original_answer = label_encoder.inverse_transform([predicted_answer_label])[0]

        st.success(f"Answer: {original_answer}")